Task1
SilnoEnamored/YADRO-Golang-course pull request #2
Opened 2024-03-30 12:20 UTC by SilnoEnamored

resolves #1
На винде работает корректно, пробовал сделать makefile для кросс компиляции, но не получилось.

2024-03-31 13:38 UTC, vbelogrudov requested changes
все неплохо, есть два недочета:
1) 
YADRO-Golang-course$ ./bin/myapp.exe -s "I'm saying: follow, followers!"
saying: follow, followers!

2) если мы будем вызывать normalization() снова и снова (в будущих заданиях), стоп слова будут загружаться на каждый вызов.

2024-03-31 13:38 UTC, vbelogrudov commented on Makefile
> +	rm -f myapp
тут наверное тоже myapp.exe лучше

2024-03-31 13:38 UTC, vbelogrudov commented on myapp/main.go
> +	words = strings.Fields(*sFlag)
лучше воспользоваться strings.FieldsFunc() , чтобы добавть разбивку по знакам пунктуации

2024-03-31 13:38 UTC, vbelogrudov commented on myapp/main.go
> +	repeated := make(map[string]struct{})
удобнее использовать map[string]bool, и тогда проверка будет выглядеть как if repeated[stemmed] {

2024-03-31 19:52 UTC, SilnoEnamored commented on myapp/main.go
> +	words = strings.Fields(*sFlag)
Попробовал сделать через strings.FieldsFunc() - не получилось, сделал отдельную функцию, которая проверяет удаляет все в строке, что не является английской буквой

2024-03-31 19:54 UTC, SilnoEnamored commented on myapp/main.go
> +	repeated := make(map[string]struct{})
я исходил из того, что при использовании strcut выделяется 0 байт, а bool использует 1
Не знаю на сколько это сильно влияет на производительность, решил, что можно и так оставить

2024-03-31 19:57 UTC, SilnoEnamored commented
@vbelogrudov 
Добавил:
 1)функцию, которая удаляет все в строке, что не является английской буквой
 2) Вынес мапу со стоп словами за функцию normalization()
 3)Исправил makefile
 Теперь при вводе : PS C:\Users\pc\GolandProjects\YADRO-Golang-course> bin/myapp.exe -s "I'm saying: follow, followers!"
say follow

2024-03-31 20:08 UTC, maxan98 commented on myapp/main.go
> +	repeated := make(map[string]struct{})
Можно, конечно, и так оставить) Есть тонкая грань между competitive и production кодом) Едва ли в данном случае нам сыграет роль 1 байт, а вот читаемость и удобство лишними не будут)

2024-03-31 20:11 UTC, maxan98 approved these changes
Супер, для первого задания - за глаза👍
В будущих заданиях, наверно, все-таки стоит разобраться с FieldsFunc - там пример из доки почти полностью ложится на наше задание. Всегда лучше переиспользовать готовое, чем изобретать велосипед :)

2024-04-01 07:17 UTC, vbelogrudov approved these changes
можно доисправлять в следующем задании

2024-04-07 11:57 UTC, closed without merging